LOG "GetAvailableAnimations: Script started. attitude=" + attitude
SET always_available_animations_instant = """PointDirection
TakeItem
LookAround
"""

SET always_available_animations_idle = """ShowTiredness
PretendShutdownAndFall
SitAndCry
BecomeTired
StartWavingArmsSides
"""

SET final_animations_list = always_available_animations_instant + always_available_animations_idle

IF attitude <= 20 THEN
    LOG "GetAvailableAnimations: Low attitude. Aggressive/dismissive animations."

	SET low_attitude_instant = """Punch
WaveInFrontOfFace
LookRandomDirection
TurnRandomDirection
"""

    SET low_attitude_idle = """LookWithContempt
ClenchFists
BecomeDisappointed
"""

    SET final_animations_list = final_animations_list + low_attitude_instant + low_attitude_idle
ELSEIF attitude > 20 AND attitude <= 50 THEN
    LOG "GetAvailableAnimations: Medium attitude. Neutral/observant animations."

    SET medium_attitude_instant = """SnapFingers
FingerGesture""" + """
SpreadArms
CloseEyes
"""

    SET medium_attitude_idle = """ArmsAtSides
FingerOnChin
ArmsForwardSides
"""

    SET final_animations_list = final_animations_list + medium_attitude_instant + medium_attitude_idle
ELSE
    LOG "GetAvailableAnimations: High attitude. Friendly/expressive animations."

    SET high_attitude_instant = """ClapHands
WaveHello
"""

    SET high_attitude_idle = """animations: ["StartDancingCool"]
animations: ["HandsClaspedFront"]
animations: ["OneHandBack"]
animations: ["CrossArms"]
"""

    SET final_animations_list = final_animations_list + high_attitude_instant + high_attitude_idle
ENDIF

RETURN final_animations_list