# src/presets/api_templates.py

API_TEMPLATES_DATA = [
    {
        "id": 1,
        "name": "Mistral AI",
        "pricing": "mixed",
        "url": "https://api.mistral.ai/v1/chat/completions",
        "default_model": "mistral-large-2512",
        "known_models": [
            "mistral-large-2407",
            "mistral-medium-2312",
        ],
        "protocol_id": "mistral_default",
        "test_url": "https://api.mistral.ai/v1/models",
        "filter_fn": "mistral_filter",
        "documentation_url": "https://docs.mistral.ai/",
        "models_url": "https://docs.mistral.ai/getting-started/models/",
        "key_url": "https://console.mistral.ai/api-keys/",
    },
    {
        "id": 2,
        "name": "OpenRouter",
        "pricing": "mixed",
        "url": "https://openrouter.ai/api/v1/chat/completions",
        "default_model": "z-ai/glm-4.5-air:free",
        "known_models": [
            "mistralai/devstral-2512:free",
            "arcee-ai/trinity-mini:free",
            "nex-agi/deepseek-v3.1-nex-n1:free",
        ],
        "protocol_id": "openrouter_default",
        "test_url": "https://openrouter.ai/api/v1/models",
        "filter_fn": "openrouter_filter",
        "documentation_url": "https://openrouter.ai/docs/quickstart",
        "models_url": "https://openrouter.ai/models",
        "key_url": "https://openrouter.ai/keys",
    },
    {
        "id": 3,
        "name": "Google AI Studio",
        "pricing": "mixed",
        "url_tpl": "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent",
        "default_model": "gemini-3-flash-preview",
        "known_models": [
            "gemini-2.5-flash",
            "gemini-2.5-pro",
            "gemini-2.5-flash-lite",
            "gemini-2.0-flash",
            "gemini-flash-latest",
        ],
        "protocol_id": "google_gemini_default",
        "test_url": "https://generativelanguage.googleapis.com/v1beta/models?key={key}",
        "filter_fn": "filter_generate_content",
        "documentation_url": "https://ai.google.dev/gemini-api/docs",
        "models_url": "https://ai.google.dev/gemini-api/docs/models/gemini",
        "key_url": "https://aistudio.google.com/apikey",
    },
    {
        "id": 4,
        "name": "Ai.iO",
        "pricing": "mixed",
        "url": "https://api.intelligence.io.solutions/api/v1/chat/completions",
        "default_model": "deepseek-ai/DeepSeek-V3.2",
        "known_models": [],
        "protocol_id": "aiio_default",
        "test_url": "https://api.intelligence.io.solutions/api/v1/models",
        "filter_fn": "aiio_filter",
        "documentation_url": "https://io.net/docs/guides/inception",
        "models_url": "https://io.net/docs/guides/intelligence/exploring-ai-models",
        "key_url": "https://ai.io.net/ai/api-keys",
    },
]