# src/presets/api_templates.py

API_TEMPLATES_DATA = [
    {
        "id": 1,
        "name": "Mistral AI",
        "pricing": "mixed",
        "url": "https://api.mistral.ai/v1/chat/completions",
        "default_model": "mistral-large-2512",
        "known_models": [
            "mistral-large-2407",
            "mistral-medium-2312",
        ],
        "protocol_id": "mistral_default",
        "test_url": "https://api.mistral.ai/v1/models",
        "filter_fn": "mistral_filter",
        "documentation_url": "https://docs.mistral.ai/",
        "models_url": "https://docs.mistral.ai/getting-started/models/",
        "key_url": "https://console.mistral.ai/api-keys/",
    },
    {
        "id": 2,
        "name": "OpenRouter",
        "pricing": "mixed",
        "url": "https://openrouter.ai/api/v1/chat/completions",
        "default_model": "nvidia/nemotron-3-super-120b-a12b:free",
        "known_models": [
            "mistralai/devstral-2512:free",
            "arcee-ai/trinity-mini:free",
            "nex-agi/deepseek-v3.1-nex-n1:free",
        ],
        "protocol_id": "openrouter_default",
        "test_url": "https://openrouter.ai/api/v1/models",
        "filter_fn": "openrouter_filter",
        "documentation_url": "https://openrouter.ai/docs/quickstart",
        "models_url": "https://openrouter.ai/models",
        "key_url": "https://openrouter.ai/keys",
    },
    {
        "id": 3,
        "name": "Google AI Studio",
        "pricing": "mixed",
        "url_tpl": "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent",
        "default_model": "gemini-3.1-flash-lite",
        "known_models": [
            "gemini-3.7-flash",
            "gemini-3.6-flash",
            "gemini-3.5-flash",
            "gemini-3.5-flash-lite",
            "gemini-3.1-flash-lite",
            "gemini-2.5-flash",
            "gemini-2.5-pro",
            "gemini-2.5-flash-lite",
            "gemini-flash-latest",
        ],
        "model_profiles": [
            {
                "id": "gemini-2.5-pro",
                "match": "gemini-2.5-pro",
                "parameters": [
                    "temperature", "max_tokens", "top_p", "top_k",
                    "presence_penalty", "frequency_penalty",
                ],
                "thinking": {
                    "transport": "budget",
                    "include_thoughts": True,
                    "disable_supported": False,
                    "disabled_budget": 128,
                    "min_budget": 128,
                    "max_budget": 32768,
                },
            },
            {
                "id": "gemini-2.5-flash",
                "match": "gemini-2.5-flash",
                "parameters": [
                    "temperature", "max_tokens", "top_p", "top_k",
                    "presence_penalty", "frequency_penalty",
                ],
                "thinking": {
                    "transport": "budget",
                    "include_thoughts": True,
                    "disable_supported": True,
                    "disabled_budget": 0,
                    "min_budget": 0,
                    "max_budget": 24576,
                },
            },
            {
                "id": "gemini-2.5-flash-lite",
                "match": "gemini-2.5-flash-lite",
                "parameters": [
                    "temperature", "max_tokens", "top_p", "top_k",
                    "presence_penalty", "frequency_penalty",
                ],
                "thinking": {
                    "transport": "budget",
                    "include_thoughts": True,
                    "disable_supported": True,
                    "disabled_budget": 0,
                    "min_budget": 512,
                    "max_budget": 24576,
                },
            },
            {
                "id": "gemini-3.1-flash-lite",
                "match": "gemini-3.1-flash-lite",
                "parameters": [
                    "max_tokens", "presence_penalty", "frequency_penalty",
                ],
                "thinking": {
                    "transport": "level",
                    "allowed_levels": ["minimal", "low", "medium", "high"],
                    "default_level": "minimal",
                    "disabled_level": "minimal",
                    "disable_supported": False,
                    "include_thoughts": True,
                },
            },
            {
                "id": "gemini-3.5-flash-lite",
                "match": "gemini-3.5-flash-lite",
                "parameters": [
                    "max_tokens", "presence_penalty", "frequency_penalty",
                ],
                "thinking": {
                    "transport": "level",
                    "allowed_levels": ["minimal", "low", "medium", "high"],
                    "default_level": "minimal",
                    "disabled_level": "minimal",
                    "disable_supported": False,
                    "include_thoughts": True,
                },
            },
            {
                "id": "gemini-3.5-flash",
                "match": "gemini-3.5-flash",
                "parameters": [
                    "max_tokens", "presence_penalty", "frequency_penalty",
                ],
                "thinking": {
                    "transport": "level",
                    "allowed_levels": ["minimal", "low", "medium", "high"],
                    "default_level": "medium",
                    "disabled_level": "minimal",
                    "include_thoughts": True,
                },
            },
            {
                "id": "gemini-3.6-flash",
                "match": "gemini-3.6-flash",
                "parameters": [
                    "max_tokens", "presence_penalty", "frequency_penalty",
                ],
                "thinking": {
                    "transport": "level",
                    "allowed_levels": ["minimal", "low", "medium", "high"],
                    "default_level": "medium",
                    "disabled_level": "minimal",
                    "disable_supported": False,
                    "include_thoughts": True,
                },
            },
            {
                "id": "gemini-3.7-flash",
                "match": "gemini-3.7-flash",
                "parameters": [
                    "max_tokens", "presence_penalty", "frequency_penalty",
                ],
                "thinking": {
                    "transport": "level",
                    "allowed_levels": ["low", "medium", "high"],
                    "default_level": "medium",
                    "disabled_level": "low",
                    "disable_supported": False,
                    "include_thoughts": True,
                },
            },
            {
                # Floating aliases must use only capabilities stable across
                # the models Google may assign to the alias.
                "id": "gemini-flash-latest",
                "match": "gemini-flash-latest",
                "parameters": ["max_tokens"],
                "thinking": {"transport": "none"},
                "native_structured_output": False,
            },
        ],
        "protocol_id": "google_gemini_default",
        "test_url": "https://generativelanguage.googleapis.com/v1beta/models?key={key}",
        "filter_fn": "filter_generate_content",
        "documentation_url": "https://ai.google.dev/gemini-api/docs",
        "models_url": "https://ai.google.dev/gemini-api/docs/models/gemini",
        "key_url": "https://aistudio.google.com/apikey",
    },
    {
        "id": 4,
        "name": "Ai.iO",
        "pricing": "paid",
        "url": "https://api.intelligence.io.solutions/api/v1/chat/completions",
        "default_model": "deepseek-ai/DeepSeek-V3.2",
        "known_models": [],
        "protocol_id": "aiio_default",
        "test_url": "https://api.intelligence.io.solutions/api/v1/models",
        "filter_fn": "aiio_filter",
        "documentation_url": "https://io.net/docs/guides/inception",
        "models_url": "https://io.net/docs/guides/intelligence/exploring-ai-models",
        "key_url": "https://ai.io.net/ai/api-keys",
    },
    {
        "id": 5,
        "name": "ProxyAPI",
        "pricing": "paid",
        "badge_kind": "ru",
        "url": "https://openai.api.proxyapi.ru/v1/chat/completions",
        "default_model": "gemini/gemini-2.0-flash",
        "known_models": [
            "anthropic/claude-sonnet-4-20250514",
            "gemini/gemini-2.0-flash",
            "openrouter/deepseek/deepseek-chat-v3.1",
        ],
        "protocol_id": "openai_compatible_default",
        "test_url": "https://openai.api.proxyapi.ru/v1/models",
        "documentation_url": "https://proxyapi.ru/docs/openai-compatible-api",
        "models_url": "https://proxyapi.ru/docs/openai-models",
        "key_url": "https://console.proxyapi.ru/",
    },
    {
        "id": 6,
        "name": "Groq",
        "pricing": "mixed",
        "url": "https://api.groq.com/openai/v1/chat/completions",
        "default_model": "llama-3.1-8b-instant",
        "known_models": [
            "llama-3.1-8b-instant",
            "llama-3.3-70b-versatile",
            "openai/gpt-oss-20b",
        ],
        "protocol_id": "openai_compatible_default",
        "test_url": "https://api.groq.com/openai/v1/models",
        "documentation_url": "https://console.groq.com/docs/openai",
        "models_url": "https://console.groq.com/docs/models",
        "key_url": "https://console.groq.com/keys",
    },
    {
        "id": 7,
        "name": "Together AI",
        "pricing": "mixed",
        "url": "https://api.together.ai/v1/chat/completions",
        "default_model": "openai/gpt-oss-20b",
        "known_models": [
            "openai/gpt-oss-20b",
            "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
            "deepseek-ai/DeepSeek-V3.1",
        ],
        "protocol_id": "openai_compatible_default",
        "test_url": "https://api.together.ai/v1/models",
        "documentation_url": "https://docs.together.ai/docs/inference/openai-compatibility",
        "models_url": "https://docs.together.ai/docs/serverless-models",
        "key_url": "https://api.together.ai/settings/api-keys",
    },
    {
        "id": 8,
        "name": "Chutes",
        "pricing": "paid",
        "url": "https://llm.chutes.ai/v1/chat/completions",
        "default_model": "deepseek-ai/DeepSeek-V3-0324",
        "known_models": [
            "deepseek-ai/DeepSeek-V3-0324",
            "deepseek-ai/DeepSeek-R1",
            "moonshotai/Kimi-K2-Instruct",
        ],
        "protocol_id": "openai_compatible_default",
        "test_url": "https://llm.chutes.ai/v1/models",
        "documentation_url": "https://chutes.ai/docs/examples/llm-chat",
        "models_url": "https://chutes.ai/docs/examples/llm-chat",
        "key_url": "https://chutes.ai/docs/getting-started/authentication",
    },
    {
        "id": 11,
        "name": "KodikRouter",
        "pricing": "paid",
        "badge_kind": "ru",
        "url": "https://api.kodikrouter.ru/v1/chat/completions",
        "default_model": "openai/gpt-4o",
        "known_models": [
            "openai/gpt-4o",
            "deepseek/deepseek-v3",
            "google/gemini-1.5-pro",
        ],
        "protocol_id": "openai_compatible_default",
        "test_url": "https://api.kodikrouter.ru/v1/models",
        "documentation_url": "https://kodikrouter.ru/docs/base",
        "models_url": "https://kodikrouter.ru/models",
        "key_url": "https://kodikrouter.ru/",
    },
    {
        "id": 9,
        "name": "LM Studio",
        "pricing": "free",
        "badge_kind": "local",
        "url": "http://127.0.0.1:1234/v1/chat/completions",
        "default_model": "",
        "known_models": [],
        "protocol_id": "lmstudio_default",
        "test_url": "http://127.0.0.1:1234/v1/models",
        "documentation_url": "https://lmstudio.ai/docs/app/api/endpoints/openai",
        "models_url": "https://lmstudio.ai/docs/app/api/endpoints/openai",
        "key_url": "",
    },
    {
        "id": 10,
        "name": "Ollama",
        "pricing": "free",
        "badge_kind": "local",
        "url": "http://127.0.0.1:11434/v1/chat/completions",
        "default_model": "llama3.1",
        "known_models": [
            "llama3.1",
            "qwen3",
            "deepseek-r1",
        ],
        "protocol_id": "openai_compatible_default",
        "test_url": "http://127.0.0.1:11434/v1/models",
        "documentation_url": "https://ollama.com/blog/openai-compatibility",
        "models_url": "https://ollama.com/search",
        "key_url": "",
    },
]
