"""Тексты лицензионного соглашения (EULA) по языкам.

Соглашение — большой многострочный текст, поэтому его непрактично гонять через
построчный каталог переводов (`translate_for_language` ищет по ключу = всей строке).
Здесь тексты лежат отдельно и выбираются по коду языка стартового экрана (#3).

Ключи — верхне-регистровые коды языков (как в `available_languages()`); для языка
без перевода используется английский фолбэк.
"""

from __future__ import annotations


_RU = """ЛИЦЕНЗИОННОЕ СОГЛАШЕНИЕ КОНЕЧНОГО ПОЛЬЗОВАТЕЛЯ

Пожалуйста, внимательно прочитайте это соглашение перед использованием программы NeuroMita.

1. ОТКАЗ ОТ ОТВЕТСТВЕННОСТИ
Разработчики NeuroMita НЕ НЕСУТ ОТВЕТСТВЕННОСТИ за контент, генерируемый искусственным интеллектом. Весь контент создается алгоритмами машинного обучения и может содержать неточности, ошибки или неприемлемый материал.

2. ОГРАНИЧЕНИЯ ИСПОЛЬЗОВАНИЯ
Вам ЗАПРЕЩАЕТСЯ использовать NeuroMita для:
• Создания незаконного, вредоносного или оскорбительного контента
• Нарушения авторских прав или интеллектуальной собственности
• Распространения дезинформации или вредоносной информации
• Любых действий, нарушающих законодательство вашей страны
• Создания контента, который может причинить вред людям

3. КОНФИДЕНЦИАЛЬНОСТЬ И ДАННЫЕ
• NeuroMita может сохранять историю чатов локально на вашем устройстве
• При использовании внешних API ваши данные могут передаваться третьим сторонам (OpenAI, Anthropic и др.)
• Мы не собираем персональные данные без вашего явного согласия
• Вы несете ответственность за безопасность своих API ключей

4. ОТКАЗ ОТ ГАРАНТИЙ
Программа предоставляется "КАК ЕСТЬ" без каких-либо гарантий, явных или подразумеваемых. Разработчики не гарантируют:
• Бесперебойную или безошибочную работу программы
• Точность или достоверность генерируемого контента
• Совместимость со всеми системами и конфигурациями

5. ОГРАНИЧЕНИЕ ОТВЕТСТВЕННОСТИ
Ни при каких обстоятельствах разработчики не несут ответственности за:
• Любые прямые, косвенные или случайные убытки
• Потерю данных или прибыли
• Ущерб, возникший в результате использования или невозможности использования программы

6. ИЗМЕНЕНИЯ И ОБНОВЛЕНИЯ
Разработчики оставляют за собой право изменять условия данного соглашения в будущих версиях программы.

7. ПРИМЕНИМОЕ ПРАВО
Данное соглашение регулируется международным правом в области программного обеспечения.

НАЖИМАЯ "ПРИНЯТЬ", ВЫ ПОДТВЕРЖДАЕТЕ, ЧТО:
• Прочитали и поняли все условия соглашения
• Принимаете на себя всю ответственность за использование программы
• Не будете использовать программу в незаконных целях"""


_EN = """END USER LICENSE AGREEMENT

Please read this agreement carefully before using NeuroMita.

1. DISCLAIMER
The developers of NeuroMita ARE NOT RESPONSIBLE for content generated by artificial intelligence. All content is created by machine learning algorithms and may contain inaccuracies, errors, or inappropriate material.

2. USAGE RESTRICTIONS
You are PROHIBITED from using NeuroMita to:
• Create illegal, harmful, or offensive content
• Violate copyrights or intellectual property
• Spread misinformation or harmful information
• Engage in any activities that violate the laws of your country
• Create content that may harm individuals

3. PRIVACY AND DATA
• NeuroMita may save chat history locally on your device
• When using external APIs, your data may be transmitted to third parties (OpenAI, Anthropic, etc.)
• We do not collect personal data without your explicit consent
• You are responsible for the security of your API keys

4. DISCLAIMER OF WARRANTIES
The software is provided "AS IS" without any warranties, express or implied. The developers do not guarantee:
• Uninterrupted or error-free operation of the software
• Accuracy or reliability of generated content
• Compatibility with all systems and configurations

5. LIMITATION OF LIABILITY
Under no circumstances shall the developers be liable for:
• Any direct, indirect, or incidental damages
• Loss of data or profits
• Damage arising from the use or inability to use the software

6. CHANGES AND UPDATES
The developers reserve the right to modify the terms of this agreement in future versions of the software.

7. GOVERNING LAW
This agreement is governed by international software law.

BY CLICKING "ACCEPT", YOU CONFIRM THAT:
• You have read and understood all terms of the agreement
• You accept full responsibility for using the software
• You will not use the software for illegal purposes"""


_DE = """ENDBENUTZER-LIZENZVEREINBARUNG

Bitte lesen Sie diese Vereinbarung sorgfältig durch, bevor Sie NeuroMita verwenden.

1. HAFTUNGSAUSSCHLUSS
Die Entwickler von NeuroMita SIND NICHT VERANTWORTLICH für von künstlicher Intelligenz generierte Inhalte. Alle Inhalte werden von Algorithmen des maschinellen Lernens erzeugt und können Ungenauigkeiten, Fehler oder unangemessenes Material enthalten.

2. NUTZUNGSBESCHRÄNKUNGEN
Es ist Ihnen UNTERSAGT, NeuroMita zu verwenden, um:
• illegale, schädliche oder beleidigende Inhalte zu erstellen
• Urheberrechte oder geistiges Eigentum zu verletzen
• Falschinformationen oder schädliche Informationen zu verbreiten
• Handlungen zu begehen, die gegen die Gesetze Ihres Landes verstoßen
• Inhalte zu erstellen, die Personen schaden können

3. DATENSCHUTZ UND DATEN
• NeuroMita kann den Chatverlauf lokal auf Ihrem Gerät speichern
• Bei Verwendung externer APIs können Ihre Daten an Dritte übermittelt werden (OpenAI, Anthropic usw.)
• Wir erheben keine personenbezogenen Daten ohne Ihre ausdrückliche Zustimmung
• Sie sind für die Sicherheit Ihrer API-Schlüssel verantwortlich

4. GEWÄHRLEISTUNGSAUSSCHLUSS
Die Software wird "WIE BESEHEN" ohne jegliche ausdrückliche oder stillschweigende Gewährleistung bereitgestellt. Die Entwickler garantieren nicht:
• einen unterbrechungs- oder fehlerfreien Betrieb der Software
• die Genauigkeit oder Zuverlässigkeit der generierten Inhalte
• die Kompatibilität mit allen Systemen und Konfigurationen

5. HAFTUNGSBESCHRÄNKUNG
Unter keinen Umständen haften die Entwickler für:
• jegliche direkte, indirekte oder zufällige Schäden
• Verlust von Daten oder Gewinnen
• Schäden, die aus der Nutzung oder Unmöglichkeit der Nutzung der Software entstehen

6. ÄNDERUNGEN UND AKTUALISIERUNGEN
Die Entwickler behalten sich das Recht vor, die Bedingungen dieser Vereinbarung in zukünftigen Versionen der Software zu ändern.

7. ANWENDBARES RECHT
Diese Vereinbarung unterliegt dem internationalen Softwarerecht.

DURCH KLICKEN AUF "AKZEPTIEREN" BESTÄTIGEN SIE, DASS SIE:
• alle Bedingungen der Vereinbarung gelesen und verstanden haben
• die volle Verantwortung für die Nutzung der Software übernehmen
• die Software nicht für illegale Zwecke verwenden werden"""


_FR = """CONTRAT DE LICENCE UTILISATEUR FINAL

Veuillez lire attentivement ce contrat avant d'utiliser NeuroMita.

1. AVERTISSEMENT
Les développeurs de NeuroMita NE SONT PAS RESPONSABLES du contenu généré par l'intelligence artificielle. Tout le contenu est créé par des algorithmes d'apprentissage automatique et peut contenir des inexactitudes, des erreurs ou des éléments inappropriés.

2. RESTRICTIONS D'UTILISATION
Il vous est INTERDIT d'utiliser NeuroMita pour :
• créer du contenu illégal, nuisible ou offensant
• violer des droits d'auteur ou la propriété intellectuelle
• diffuser de la désinformation ou des informations nuisibles
• mener toute activité qui enfreint les lois de votre pays
• créer du contenu susceptible de nuire à des personnes

3. CONFIDENTIALITÉ ET DONNÉES
• NeuroMita peut enregistrer l'historique des conversations localement sur votre appareil
• Lors de l'utilisation d'API externes, vos données peuvent être transmises à des tiers (OpenAI, Anthropic, etc.)
• Nous ne collectons pas de données personnelles sans votre consentement explicite
• Vous êtes responsable de la sécurité de vos clés API

4. EXCLUSION DE GARANTIES
Le logiciel est fourni "EN L'ÉTAT", sans aucune garantie, expresse ou implicite. Les développeurs ne garantissent pas :
• un fonctionnement ininterrompu ou sans erreur du logiciel
• l'exactitude ou la fiabilité du contenu généré
• la compatibilité avec tous les systèmes et configurations

5. LIMITATION DE RESPONSABILITÉ
En aucun cas les développeurs ne sauraient être tenus responsables de :
• tout dommage direct, indirect ou accessoire
• la perte de données ou de profits
• les dommages résultant de l'utilisation ou de l'impossibilité d'utiliser le logiciel

6. MODIFICATIONS ET MISES À JOUR
Les développeurs se réservent le droit de modifier les conditions du présent contrat dans les futures versions du logiciel.

7. DROIT APPLICABLE
Ce contrat est régi par le droit international du logiciel.

EN CLIQUANT SUR "ACCEPTER", VOUS CONFIRMEZ QUE :
• vous avez lu et compris toutes les conditions du contrat
• vous assumez l'entière responsabilité de l'utilisation du logiciel
• vous n'utiliserez pas le logiciel à des fins illégales"""


_UK = """ЛІЦЕНЗІЙНА УГОДА КІНЦЕВОГО КОРИСТУВАЧА

Будь ласка, уважно прочитайте цю угоду перед використанням програми NeuroMita.

1. ВІДМОВА ВІД ВІДПОВІДАЛЬНОСТІ
Розробники NeuroMita НЕ НЕСУТЬ ВІДПОВІДАЛЬНОСТІ за контент, згенерований штучним інтелектом. Увесь контент створюється алгоритмами машинного навчання і може містити неточності, помилки або неприйнятний матеріал.

2. ОБМЕЖЕННЯ ВИКОРИСТАННЯ
Вам ЗАБОРОНЕНО використовувати NeuroMita для:
• Створення незаконного, шкідливого або образливого контенту
• Порушення авторських прав або інтелектуальної власності
• Поширення дезінформації або шкідливої інформації
• Будь-яких дій, що порушують законодавство вашої країни
• Створення контенту, який може завдати шкоди людям

3. КОНФІДЕНЦІЙНІСТЬ І ДАНІ
• NeuroMita може зберігати історію чатів локально на вашому пристрої
• Під час використання зовнішніх API ваші дані можуть передаватися третім сторонам (OpenAI, Anthropic тощо)
• Ми не збираємо персональні дані без вашої явної згоди
• Ви несете відповідальність за безпеку своїх API-ключів

4. ВІДМОВА ВІД ГАРАНТІЙ
Програма надається "ЯК Є" без будь-яких гарантій, явних чи неявних. Розробники не гарантують:
• Безперебійну або безпомилкову роботу програми
• Точність або достовірність згенерованого контенту
• Сумісність з усіма системами та конфігураціями

5. ОБМЕЖЕННЯ ВІДПОВІДАЛЬНОСТІ
За жодних обставин розробники не несуть відповідальності за:
• Будь-які прямі, непрямі або випадкові збитки
• Втрату даних або прибутку
• Шкоду, що виникла внаслідок використання або неможливості використання програми

6. ЗМІНИ ТА ОНОВЛЕННЯ
Розробники залишають за собою право змінювати умови цієї угоди в майбутніх версіях програми.

7. ЗАСТОСОВНЕ ПРАВО
Ця угода регулюється міжнародним правом у сфері програмного забезпечення.

НАТИСКАЮЧИ "ПРИЙНЯТИ", ВИ ПІДТВЕРДЖУЄТЕ, ЩО:
• Прочитали та зрозуміли всі умови угоди
• Берете на себе всю відповідальність за використання програми
• Не використовуватимете програму в незаконних цілях"""


_EL = """ΑΔΕΙΑ ΧΡΗΣΗΣ ΤΕΛΙΚΟΥ ΧΡΗΣΤΗ

Παρακαλούμε διαβάστε προσεκτικά αυτή τη συμφωνία πριν χρησιμοποιήσετε το NeuroMita.

1. ΑΠΟΠΟΙΗΣΗ ΕΥΘΥΝΗΣ
Οι προγραμματιστές του NeuroMita ΔΕΝ ΕΙΝΑΙ ΥΠΕΥΘΥΝΟΙ για περιεχόμενο που δημιουργείται από την τεχνητή νοημοσύνη. Όλο το περιεχόμενο δημιουργείται από αλγορίθμους μηχανικής μάθησης και ενδέχεται να περιέχει ανακρίβειες, σφάλματα ή ακατάλληλο υλικό.

2. ΠΕΡΙΟΡΙΣΜΟΙ ΧΡΗΣΗΣ
ΑΠΑΓΟΡΕΥΕΤΑΙ να χρησιμοποιείτε το NeuroMita για:
• Δημιουργία παράνομου, επιβλαβούς ή προσβλητικού περιεχομένου
• Παραβίαση πνευματικών δικαιωμάτων ή πνευματικής ιδιοκτησίας
• Διάδοση παραπληροφόρησης ή επιβλαβών πληροφοριών
• Οποιαδήποτε ενέργεια που παραβιάζει τους νόμους της χώρας σας
• Δημιουργία περιεχομένου που μπορεί να βλάψει ανθρώπους

3. ΑΠΟΡΡΗΤΟ ΚΑΙ ΔΕΔΟΜΕΝΑ
• Το NeuroMita μπορεί να αποθηκεύει το ιστορικό συνομιλιών τοπικά στη συσκευή σας
• Κατά τη χρήση εξωτερικών API, τα δεδομένα σας ενδέχεται να μεταδοθούν σε τρίτους (OpenAI, Anthropic κ.λπ.)
• Δεν συλλέγουμε προσωπικά δεδομένα χωρίς τη ρητή συγκατάθεσή σας
• Είστε υπεύθυνοι για την ασφάλεια των κλειδιών API σας

4. ΑΠΟΠΟΙΗΣΗ ΕΓΓΥΗΣΕΩΝ
Το λογισμικό παρέχεται "ΩΣ ΕΧΕΙ" χωρίς καμία εγγύηση, ρητή ή σιωπηρή. Οι προγραμματιστές δεν εγγυώνται:
• Αδιάλειπτη ή χωρίς σφάλματα λειτουργία του λογισμικού
• Ακρίβεια ή αξιοπιστία του παραγόμενου περιεχομένου
• Συμβατότητα με όλα τα συστήματα και τις διαμορφώσεις

5. ΠΕΡΙΟΡΙΣΜΟΣ ΕΥΘΥΝΗΣ
Σε καμία περίπτωση οι προγραμματιστές δεν ευθύνονται για:
• Οποιαδήποτε άμεση, έμμεση ή τυχαία ζημία
• Απώλεια δεδομένων ή κερδών
• Ζημία που προκύπτει από τη χρήση ή την αδυναμία χρήσης του λογισμικού

6. ΑΛΛΑΓΕΣ ΚΑΙ ΕΝΗΜΕΡΩΣΕΙΣ
Οι προγραμματιστές διατηρούν το δικαίωμα να τροποποιήσουν τους όρους της παρούσας συμφωνίας σε μελλοντικές εκδόσεις του λογισμικού.

7. ΕΦΑΡΜΟΣΤΕΟ ΔΙΚΑΙΟ
Η παρούσα συμφωνία διέπεται από το διεθνές δίκαιο λογισμικού.

ΚΑΝΟΝΤΑΣ ΚΛΙΚ ΣΤΟ "ΑΠΟΔΟΧΗ", ΕΠΙΒΕΒΑΙΩΝΕΤΕ ΟΤΙ:
• Διαβάσατε και κατανοήσατε όλους τους όρους της συμφωνίας
• Αναλαμβάνετε την πλήρη ευθύνη για τη χρήση του λογισμικού
• Δεν θα χρησιμοποιήσετε το λογισμικό για παράνομους σκοπούς"""


_ZH = """最终用户许可协议

在使用 NeuroMita 之前，请仔细阅读本协议。

1. 免责声明
NeuroMita 的开发者对人工智能生成的内容不承担任何责任。所有内容均由机器学习算法生成，可能包含不准确之处、错误或不当材料。

2. 使用限制
禁止您将 NeuroMita 用于：
• 创建非法、有害或冒犯性内容
• 侵犯版权或知识产权
• 传播虚假信息或有害信息
• 任何违反您所在国家法律的行为
• 创建可能伤害他人的内容

3. 隐私与数据
• NeuroMita 可能会在您的设备上本地保存聊天记录
• 使用外部 API 时，您的数据可能会传输给第三方（OpenAI、Anthropic 等）
• 未经您的明确同意，我们不会收集个人数据
• 您有责任保护自己的 API 密钥安全

4. 不提供保证
本软件按“原样”提供，不附带任何明示或暗示的保证。开发者不保证：
• 软件不间断或无错误地运行
• 生成内容的准确性或可靠性
• 与所有系统和配置的兼容性

5. 责任限制
在任何情况下，开发者均不对以下情况承担责任：
• 任何直接、间接或附带的损失
• 数据或利润的损失
• 因使用或无法使用本软件而造成的损害

6. 变更与更新
开发者保留在软件的未来版本中修改本协议条款的权利。

7. 适用法律
本协议受国际软件法律管辖。

点击“接受”即表示您确认：
• 您已阅读并理解本协议的所有条款
• 您对软件的使用承担全部责任
• 您不会将本软件用于非法目的"""


_JA = """エンドユーザー使用許諾契約

NeuroMita をご利用になる前に、本契約をよくお読みください。

1. 免責事項
NeuroMita の開発者は、人工知能によって生成されたコンテンツについて一切の責任を負いません。すべてのコンテンツは機械学習アルゴリズムによって生成され、不正確な点、誤り、または不適切な内容が含まれる場合があります。

2. 使用上の制限
以下の目的で NeuroMita を使用することを禁止します：
• 違法、有害、または攻撃的なコンテンツの作成
• 著作権または知的財産権の侵害
• 誤情報または有害な情報の拡散
• お住まいの国の法律に違反する一切の行為
• 人々に害を及ぼす可能性のあるコンテンツの作成

3. プライバシーとデータ
• NeuroMita はチャット履歴をお使いのデバイスにローカルで保存する場合があります
• 外部 API を使用する場合、お客様のデータは第三者（OpenAI、Anthropic など）に送信される場合があります
• 当社はお客様の明示的な同意なしに個人データを収集しません
• API キーのセキュリティはお客様の責任で管理してください

4. 保証の否認
本ソフトウェアは、明示または黙示を問わず、いかなる保証もなく「現状のまま」提供されます。開発者は以下を保証しません：
• ソフトウェアの中断のない、またはエラーのない動作
• 生成されたコンテンツの正確性または信頼性
• すべてのシステムおよび構成との互換性

5. 責任の制限
いかなる場合も、開発者は以下について責任を負いません：
• 直接的、間接的、または付随的な損害
• データまたは利益の損失
• 本ソフトウェアの使用または使用不能から生じる損害

6. 変更および更新
開発者は、本ソフトウェアの将来のバージョンで本契約の条件を変更する権利を留保します。

7. 準拠法
本契約は、ソフトウェアに関する国際法に準拠します。

「同意する」をクリックすることにより、お客様は以下を確認します：
• 本契約のすべての条件を読み、理解したこと
• 本ソフトウェアの使用に関するすべての責任を負うこと
• 本ソフトウェアを違法な目的で使用しないこと"""


_KO = """최종 사용자 라이선스 계약

NeuroMita를 사용하기 전에 본 계약을 주의 깊게 읽어 주십시오.

1. 면책 조항
NeuroMita 개발자는 인공지능이 생성한 콘텐츠에 대해 책임을 지지 않습니다. 모든 콘텐츠는 머신러닝 알고리즘에 의해 생성되며 부정확성, 오류 또는 부적절한 자료를 포함할 수 있습니다.

2. 사용 제한
다음의 목적으로 NeuroMita를 사용하는 것이 금지됩니다:
• 불법적이거나 유해하거나 모욕적인 콘텐츠 생성
• 저작권 또는 지적 재산권 침해
• 허위 정보 또는 유해한 정보의 유포
• 귀하의 국가 법률을 위반하는 모든 행위
• 사람에게 해를 끼칠 수 있는 콘텐츠 생성

3. 개인정보 및 데이터
• NeuroMita는 채팅 기록을 귀하의 기기에 로컬로 저장할 수 있습니다
• 외부 API를 사용할 때 귀하의 데이터가 제3자(OpenAI, Anthropic 등)에게 전송될 수 있습니다
• 당사는 귀하의 명시적 동의 없이 개인 데이터를 수집하지 않습니다
• API 키의 보안은 귀하의 책임입니다

4. 보증의 부인
본 소프트웨어는 명시적이든 묵시적이든 어떠한 보증도 없이 "있는 그대로" 제공됩니다. 개발자는 다음을 보증하지 않습니다:
• 소프트웨어의 중단 없는 또는 오류 없는 작동
• 생성된 콘텐츠의 정확성 또는 신뢰성
• 모든 시스템 및 구성과의 호환성

5. 책임의 제한
어떠한 경우에도 개발자는 다음에 대해 책임을 지지 않습니다:
• 모든 직접적, 간접적 또는 부수적 손해
• 데이터 또는 이익의 손실
• 소프트웨어의 사용 또는 사용 불가로 인해 발생한 손해

6. 변경 및 업데이트
개발자는 향후 소프트웨어 버전에서 본 계약의 조건을 변경할 권리를 보유합니다.

7. 준거법
본 계약은 소프트웨어에 관한 국제법의 적용을 받습니다.

"수락"을 클릭함으로써 귀하는 다음을 확인합니다:
• 본 계약의 모든 조건을 읽고 이해했음
• 소프트웨어 사용에 대한 모든 책임을 부담함
• 소프트웨어를 불법적인 목적으로 사용하지 않을 것임"""


EULA_TEXTS: dict[str, str] = {
    "RU": _RU,
    "EN": _EN,
    "DE": _DE,
    "FR": _FR,
    "UK": _UK,
    "EL": _EL,
    "ZH": _ZH,
    "JA": _JA,
    "KO": _KO,
}


def get_eula_text(lang: str) -> str:
    """Текст соглашения для языка (код любого регистра). Фолбэк — английский."""
    code = str(lang or "RU").strip().upper()
    return EULA_TEXTS.get(code) or EULA_TEXTS["EN"]
